version: "3.5"

services:
  wgdashboard:
    image: ghcr.io/royalcat/wgdashboard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped 
    volumes:
      - config:/etc/wireguard
    ports:
      - 10086:10086
      - 51820:51820/udp

volumes:
  config: